# Configuration for auto-assign action
# https://github.com/kentaro-m/auto-assign-action

# Reviewers to assign to PRs
reviewers:
  - yashielsookdeo

# Assignees for PRs (usually the PR author, but can be overridden)
assignees:
  - yashielsookdeo

# Number of reviewers to assign (if you have multiple reviewers)
numberOfReviewers: 1

# Number of assignees to assign
numberOfAssignees: 1

# Skip draft PRs
skipDraftPR: true

# Add reviewers as assignees
addReviewersAsAssignees: false

# Add assignees as reviewers
addAssigneesAsReviewers: false

# Skip PRs with specific labels
skipLabels:
  - 'skip-review'
  - 'wip'
  - 'work-in-progress'

# Only assign reviewers to PRs with specific labels (optional)
# includeLabels:
#   - 'needs-review'

# Custom assignment rules based on file patterns
fileAssignments:
  # Frontend changes
  'src/components/**/*':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

  # Backend/API changes
  'src/services/**/*':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

  # Configuration changes
  'vite.config.js':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

  'package.json':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

  # CI/CD changes
  '.github/**/*':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

  # Documentation changes
  '**/*.md':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

  # Security related files
  '.github/workflows/security-scan.yml':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

  # Environment files
  '.env*':
    reviewers:
      - yashielsookdeo
    assignees:
      - yashielsookdeo

# Custom messages (optional)
# reviewRequestMessage: |
#   Thanks for your contribution! 🎉
#   A reviewer has been automatically assigned to your PR.

# assigneeRequestMessage: |
#   You've been assigned to this PR. Please review when you have time.

# Run only on specific events
runOnEvents:
  - opened
  - ready_for_review

# Skip if PR author is in this list
skipUsers:
  - dependabot[bot]
  - github-actions[bot]
