version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 10
    reviewers:
      - "yashielsookdeo"
    assignees:
      - "yashielsookdeo"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    milestone: 1
    target-branch: "develop"
    versioning-strategy: "increase"
    
    # Group updates for better PR management
    groups:
      # Group React ecosystem updates
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        
      # Group build tools
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "rollup*"
          - "esbuild*"
        
      # Group linting and formatting tools
      code-quality:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "@typescript-eslint/*"
        
      # Group testing tools
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "vitest*"
          - "playwright*"
        
      # Group minor and patch updates for all other dependencies
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    
    # Ignore specific dependencies that need manual updates
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-router-dom"
        update-types: ["version-update:semver-major"]
      
      # Ignore specific versions that are known to have issues
      - dependency-name: "vite"
        versions: ["5.0.0", "5.0.1"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 5
    reviewers:
      - "yashielsookdeo"
    assignees:
      - "yashielsookdeo"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"
      - "automated"
    target-branch: "develop"

  # Enable version updates for Docker (if using Docker in the future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 3
    reviewers:
      - "yashielsookdeo"
    commit-message:
      prefix: "docker"
    labels:
      - "docker"
      - "automated"
    target-branch: "develop"
