name: Deploy to Production

on:
  push:
    branches: [ production ]
  # Pull requests do not trigger deployment - only merged commits to production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Create production environment file
      run: |
        cp .env.production .env.local
        echo "Environment variables configured for production build"
        echo "Verifying TMDB API key is present..."
        grep -q "VITE_TMDB_API_KEY=" .env.local && echo "✅ TMDB API key found" || echo "❌ TMDB API key missing"

    - name: Build project
      run: npm run build:production
      env:
        NODE_ENV: production

    - name: Verify build output
      run: |
        echo "Checking if build was successful..."
        ls -la dist/
        echo "Verifying environment variables are embedded in build..."
        if grep -r "20aed25855723af6f6a4dcdad0f17b86" dist/ > /dev/null; then
          echo "✅ TMDB API key found in build output"
        else
          echo "❌ TMDB API key NOT found in build output"
          exit 1
        fi
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.skyner.co.za
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /bumblebeefoundation.co.za/
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
          **/*.md
          
    - name: Notify deployment success
      if: success()
      run: |
        echo "🚀 Deployment successful!"
        echo "Site should be live at: https://bumblebeefoundation.co.za"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        echo "Please check the logs above for errors."
