name: 🚀 Production Deploy

on:
  push:
    branches: [ production ]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10 # Fail fast if something goes wrong

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install & Build
      run: |
        npm ci --prefer-offline --no-audit
        cp .env.production .env.local
        npm run build:production
      env:
        NODE_ENV: production

    - name: Verify Build
      run: |
        [ -d "dist" ] && [ "$(ls -A dist)" ] || { echo "❌ Build failed"; exit 1; }
        echo "✅ Build successful ($(du -sh dist | cut -f1))"

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.skyner.co.za
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /bumblebeefoundation.co.za/
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/node_modules/**
          **/.env*

    - name: Status
      run: echo "🚀 Deployed to https://bumblebeefoundation.co.za"
